---
title: "Data curation for wearable"
author: "Cindy Barker"
date: "12/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Summary

This project includes a R data cleaning script to create tidy data for wearable computing. 

The data set that it cleanses is from Samsung Galaxy S smartphone. A full description is available at the [site](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones). 

The data for the project can be downloaded from [here](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip).

### R script 
run_analysis.R is the script that performs the data cleansing. 
It contains below functions:

* main: the driver function which downloads the zip file, contruct the dataframes, clean up names/labels, extract related fields and finally return a new dataframe by grouping the two index fields. 
* prepareDataFile: helper function to download and unzip data files
* loadVector: helper function to create vendor from txt file
* loadDataFrame: helper function to create dataframe from txt file
* prepareLabels: helper function to clean up labels
